[package]
name = "format-whatsapp-export"
version = "0.1.0"
edition = "2024"
default-run = "format-whatsapp-export"

[dependencies]
rfd = "0.15.4"
win-utf8-rs = "0.2.0"
msg_parser = { workspace = true }

[dev-dependencies]
tempfile = "3"
